# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luizfelipe/ike

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luizfelipe/ike

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luizfelipe/ike/CMakeFiles /home/luizfelipe/ike//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luizfelipe/ike/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iked

# Build rule for target.
iked: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iked
.PHONY : iked

# fast build rule for target.
iked/fast:
	$(MAKE) $(MAKESILENT) -f source/iked/CMakeFiles/iked.dir/build.make source/iked/CMakeFiles/iked.dir/build
.PHONY : iked/fast

#=============================================================================
# Target rules for targets named ConfParser

# Build rule for target.
ConfParser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ConfParser
.PHONY : ConfParser

# fast build rule for target.
ConfParser/fast:
	$(MAKE) $(MAKESILENT) -f source/iked/CMakeFiles/ConfParser.dir/build.make source/iked/CMakeFiles/ConfParser.dir/build
.PHONY : ConfParser/fast

#=============================================================================
# Target rules for targets named ikec

# Build rule for target.
ikec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ikec
.PHONY : ikec

# fast build rule for target.
ikec/fast:
	$(MAKE) $(MAKESILENT) -f source/ikec/CMakeFiles/ikec.dir/build.make source/ikec/CMakeFiles/ikec.dir/build
.PHONY : ikec/fast

#=============================================================================
# Target rules for targets named ss_ike

# Build rule for target.
ss_ike: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ss_ike
.PHONY : ss_ike

# fast build rule for target.
ss_ike/fast:
	$(MAKE) $(MAKESILENT) -f source/libike/CMakeFiles/ss_ike.dir/build.make source/libike/CMakeFiles/ss_ike.dir/build
.PHONY : ss_ike/fast

#=============================================================================
# Target rules for targets named ss_ip

# Build rule for target.
ss_ip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ss_ip
.PHONY : ss_ip

# fast build rule for target.
ss_ip/fast:
	$(MAKE) $(MAKESILENT) -f source/libip/CMakeFiles/ss_ip.dir/build.make source/libip/CMakeFiles/ss_ip.dir/build
.PHONY : ss_ip/fast

#=============================================================================
# Target rules for targets named ss_idb

# Build rule for target.
ss_idb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ss_idb
.PHONY : ss_idb

# fast build rule for target.
ss_idb/fast:
	$(MAKE) $(MAKESILENT) -f source/libidb/CMakeFiles/ss_idb.dir/build.make source/libidb/CMakeFiles/ss_idb.dir/build
.PHONY : ss_idb/fast

#=============================================================================
# Target rules for targets named ss_ith

# Build rule for target.
ss_ith: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ss_ith
.PHONY : ss_ith

# fast build rule for target.
ss_ith/fast:
	$(MAKE) $(MAKESILENT) -f source/libith/CMakeFiles/ss_ith.dir/build.make source/libith/CMakeFiles/ss_ith.dir/build
.PHONY : ss_ith/fast

#=============================================================================
# Target rules for targets named ss_log

# Build rule for target.
ss_log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ss_log
.PHONY : ss_log

# fast build rule for target.
ss_log/fast:
	$(MAKE) $(MAKESILENT) -f source/liblog/CMakeFiles/ss_log.dir/build.make source/liblog/CMakeFiles/ss_log.dir/build
.PHONY : ss_log/fast

#=============================================================================
# Target rules for targets named ss_pfk

# Build rule for target.
ss_pfk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ss_pfk
.PHONY : ss_pfk

# fast build rule for target.
ss_pfk/fast:
	$(MAKE) $(MAKESILENT) -f source/libpfk/CMakeFiles/ss_pfk.dir/build.make source/libpfk/CMakeFiles/ss_pfk.dir/build
.PHONY : ss_pfk/fast

#=============================================================================
# Target rules for targets named qikea

# Build rule for target.
qikea: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qikea
.PHONY : qikea

# fast build rule for target.
qikea/fast:
	$(MAKE) $(MAKESILENT) -f source/qikea/CMakeFiles/qikea.dir/build.make source/qikea/CMakeFiles/qikea.dir/build
.PHONY : qikea/fast

#=============================================================================
# Target rules for targets named qikec

# Build rule for target.
qikec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qikec
.PHONY : qikec

# fast build rule for target.
qikec/fast:
	$(MAKE) $(MAKESILENT) -f source/qikec/CMakeFiles/qikec.dir/build.make source/qikec/CMakeFiles/qikec.dir/build
.PHONY : qikec/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ConfParser"
	@echo "... ikec"
	@echo "... iked"
	@echo "... qikea"
	@echo "... qikec"
	@echo "... ss_idb"
	@echo "... ss_ike"
	@echo "... ss_ip"
	@echo "... ss_ith"
	@echo "... ss_log"
	@echo "... ss_pfk"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

